kind: Deployment
apiVersion: apps/v1
metadata:
  name: fullstack-admin-web
  namespace: ${NAMESPACE}
  labels:
    app: fullstack-admin-web
spec:
  selector:
    matchLabels:
      app: fullstack-admin-web
  replicas: 1
  template:
    metadata:
      labels:
        app: fullstack-admin-web
    spec:
      containers:
        - name: fullstack-admin-web
          image: ${IMAGE}
          ports:
            - containerPort: 80
          resources:
            requests:
              # 1核心的CPU=1000m
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 100Mi
          # 容器的异常终止消息的路径，默认在 /dev/termination-log
          terminationMessagePath: /dev/termination-log
          # 容器终止消息的来源路径和策略，默认 File
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      # 优雅停机等待时间
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-admin-web
  namespace: ${NAMESPACE}
  labels:
    app: fullstack-admin-web
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000
  selector:
    app: fullstack-admin-web
  type: NodePort
  sessionAffinity: None
